name: Deploy sitio estático a Azure Web App - Formulario-Calificaciones-Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Formulario-Calificaciones-Web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./public_html
